"
""TPI"" es el paquete que contiene todo lo relacionado al
desarrollo del juego pedido por la cátedra como parte del
Trabajo Práctico Integrador.

Contiene las siguientes etiquetas para agrupar clases:
* ""Elementos"": contiene clases para modelar objetos
  como un jugador, o el estado global del juego.
* ""Menus"": contiene las clases utilizadas para definir
  los distintos menús o pantallas con las que cuenta el
  juego, como la pantalla inicial.
"
Class {
	#name : 'ManifestTPI',
	#superclass : 'PackageManifest',
	#category : 'TPI-Manifest',
	#package : 'TPI',
	#tag : 'Manifest'
}
